### ISSUE TITLE
Getting an error using with Nuxt

### ISSUE THREAD

**Issue by daletom** [junkboy0315/vue-compare-image#10]
Hi, 

I got this to work in a codesandbox with Vue, but tried adding it to my nuxt project and am having issues.  Below is an example of the code I am using. I also did the import and export scripts correctly I believe. A screen shot is below of the error. You have any success doing this in nuxt yourself?

```
<nuxt-link to="/cc/living1"
      ><VueCompareImage :style="{ maxWidth: '500px' }"
        leftImage="https://tom.imgix.net/living1before.jpg?w=1000&h=1000&fit=crop&auto=format%2Ccompress"
        rightImage="https://tom.imgix.net/living1after.jpg?w=1000&h=1000&fit=crop&auto=format%2Ccompress"
        alt="Living Room 1 image before and after"
        hover
    /></nuxt-link>
```

```
<script>
import VueCompareImage from 'vue-compare-image';

export default {
  components: { VueCompareImage },
  head() {
```

![image](https://user-images.githubusercontent.com/13734256/80933530-f4bf6f80-8d78-11ea-8a2b-e81a60c2a98b.png)

**Comment by daletom** [comment]
Ohh, maybe the issue is that this doesnt work with SSR?

**Comment by daletom** [comment]
Hmm, maybe not. 
I tried adding it as a plugin and forcing it to not do ssr.
```
import Vue from 'vue'
import { VueCompareImage } from 'vue-compare-image'
Vue.component('leftImage', VueCompareImage)
Vue.component('rightImage', VueCompareImage)
```
then in nuxt.config
```
plugins: [ { src: '~plugins//vue-compare-image', ssr: false }
  ],
```

**Comment by daletom** [comment]
Ok, I was able to get rid of the Document reference error by doing the ssr: false plugin, I was just forgetting Vue.use(VueCompareImage) in the plugin section.

But the page is simply blank now. When inspection, I do see this code:

![image](https://user-images.githubusercontent.com/13734256/81467221-27f46b00-918c-11ea-9760-9d4318b10cb1.png)

Seems like it's not understanding that the VueCompareImage should be converted to an image tag.

**Comment by steveDL** [comment]
@daletom I got this working with the following 

`import Vue from 'vue'
import VueCompareImage from 'vue-compare-image'

Vue.component('VueCompareImage', VueCompareImage)
`

**Comment by daletom** [comment]
awesome, got it working here @steveDL https://github.com/daletom/vuecompare-testing. thanks for the help! Now time to put that into my home page.
